### ISSUE TITLE
Bug: Label generation in biblatex/biber

### ISSUE THREAD

**Issue by sstrecker** [sstrecker/emisa-latex-package#18]
See problem of disambiguation with names. 

Example: Dietz, Jan L. G. and Dietz, J. L. G.  

The first bibentry produces a wrong label: (Albani, Jan L. G. Dietz and Verelst 2011) instead of (Albani, Dietz and Verelst 2011).

@incollection{AlbaniDietzVerelst2011,
    Address = {Berlin, Heidelberg},
    Author = {Albani, Antonia and Dietz, Jan L. G. and Verelst, J.},
    Booktitle = {Advances in Enterprise Engineering V},
    Editor = {Albani, Antonia and Dietz, J. L. G.},
    Publisher = {Springer},
    Title = {Preface},
    Year = {2011}}

@book{Dietz2006-masked,
    Address = {Berlin, Heidelberg},
    Author = {Dietz, J. L. G.},
    Date-Modified = {2016-01-16 20:44:31 +0100},
    Publisher = {Springer},
    Title = {Enterprise Ontology - Theory and Methodology},
    Year = {2006}}

**Comment by sieversMartin** [comment]
From the example @bternes sent me I conclude, that there is no general solution. This means one can only react when this problem arises for a concrete article. However, instead of using a `DeclareSourceMap` routine for every author I would suggest to rather edit the author's BibTeX file and add a small note into the documentation.

**Comment by sstrecker** [comment]
I wrote a note in the instructions. See commit 839d8a4
